version: '3.4'

services: 
    rabbitmq:
        container_name: 'rabbitmq'
        image: rabbitmq:3-management-alpine
        volumes: 
            - mq_data:/var/lib/rabbitmq/mnesia
        ports: 
            - "15672:15672"
            - "5672:5672"
        networks: 
            - logs
        environment: 
            - RABBITMQ_DEFAULT_USER=tico
            - RABBITMQ_DEFAULT_PASS=tico123
            - RABBITMQ_DEFAULT_VHOST=ticoVHost
volumes: 
    mq_data:
networks: 
    logs:
        driver: bridge
        
                